name: logger_example
description: "A project demonstrating the capabilities of the logger."
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  syn_log_interface: ^1.0.3
  syn_logger_file_writer: ^1.0.1
  syn_thread_safe_logger: ^1.0.0

flutter:
  uses-material-design: true
dev_dependencies:
  dart_code_linter: ^2.0.0
  lint: ^2.8.0
